(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.XFLOW_CASE_DATA = api;
})(typeof window !== "undefined" ? window : globalThis, function () {
  const vacationHomes = [
    ["roma-stay-campo-fiori", "Casa Campo de Fiori 12", "Centro storico", 0.92],
    ["roma-stay-coronari", "Casa Via dei Coronari", "Navona", 0.86],
    ["roma-stay-banchi", "Casa Banchi Vecchi", "Regola", 0.8],
    ["roma-stay-giulia", "Casa Via Giulia", "Regola", 0.88],
    ["roma-stay-ripetta", "Casa Ripetta", "Campo Marzio", 0.84],
    ["roma-stay-leutari", "Casa Leutari", "Parione", 0.79],
    ["roma-stay-pellegrino", "Casa Pellegrino", "Campo de Fiori", 0.9],
    ["roma-stay-panico", "Casa Panico", "Ponte", 0.75],
    ["roma-stay-scala", "Casa della Scala", "Trastevere", 0.87],
    ["roma-stay-lungara", "Casa Lungara", "Trastevere", 0.83],
    ["roma-stay-serpenti", "Casa Serpenti", "Monti", 0.81],
    ["roma-stay-madonna-monti", "Casa Madonna dei Monti", "Monti", 0.89],
    ["roma-stay-urbana", "Casa Urbana", "Monti", 0.78],
    ["roma-stay-cavour", "Casa Cavour", "Esquilino", 0.76],
    ["roma-stay-merulana", "Casa Merulana", "Esquilino", 0.82],
    ["roma-stay-labicana", "Casa Labicana", "Colosseo", 0.85],
    ["roma-stay-celso", "Casa San Celso", "Borgo", 0.8],
    ["roma-stay-borgo-pio", "Casa Borgo Pio", "Vaticano", 0.91],
    ["roma-stay-via-ottaviano", "Casa Ottaviano", "Prati", 0.86],
    ["roma-stay-cola-rienzo", "Casa Cola di Rienzo", "Prati", 0.77],
    ["roma-stay-marmorata", "Casa Marmorata", "Testaccio", 0.83],
    ["roma-stay-aventino", "Casa Aventino", "Aventino", 0.74],
    ["roma-stay-piramide", "Casa Piramide", "Ostiense", 0.82],
    ["roma-stay-garbatella", "Casa Garbatella", "Garbatella", 0.7],
    ["roma-stay-coppede", "Casa Coppede", "Trieste", 0.73],
    ["roma-stay-po", "Casa Via Po", "Parioli", 0.68],
    ["roma-stay-sannio", "Casa Sannio", "San Giovanni", 0.8],
    ["roma-stay-appia", "Casa Appia", "San Giovanni", 0.78],
    ["roma-stay-pigneto", "Casa Pigneto", "Pigneto", 0.72],
    ["roma-stay-casilina", "Casa Casilina", "Pigneto", 0.69],
  ].map(([id, name, area, occupancy]) => ({ id, name, type: "Casa vacanza", area, rooms: 1, occupancy, status: "active" }));

  const guesthouses = [
    ["affittacamere-tramonto", "Affittacamere Tramonto", "Prati", 0.9],
    ["affittacamere-liberty", "Affittacamere Liberty", "Trastevere", 0.88],
    ["affittacamere-ponte", "Affittacamere Ponte", "Navona", 0.86],
    ["affittacamere-argento", "Affittacamere Argento", "Monti", 0.82],
    ["affittacamere-rione", "Affittacamere Rione", "Testaccio", 0.79],
    ["affittacamere-ostiense", "Affittacamere Ostiense", "Ostiense", 0.84],
    ["affittacamere-luce", "Affittacamere Luce", "San Giovanni", 0.81],
    ["affittacamere-tevere", "Affittacamere Tevere", "Borgo", 0.87],
    ["affittacamere-pini", "Affittacamere Pini", "Parioli", 0.76],
    ["affittacamere-mura", "Affittacamere Mura", "Termini", 0.85],
  ].map(([id, name, area, occupancy]) => ({ id, name, type: "Affittacamere", area, rooms: 10, occupancy, status: "attention" }));

  const properties = [
    { id: "hotel-aurora", name: "Hotel Aurora", type: "Hotel", area: "Roma Prati", rooms: 50, occupancy: 0.86, status: "active" },
    { id: "hotel-velario", name: "Hotel Velario", type: "Hotel", area: "Trastevere", rooms: 30, occupancy: 0.91, status: "attention" },
    { id: "hotel-giardino", name: "Hotel Giardino", type: "Hotel", area: "Monti", rooms: 20, occupancy: 0.78, status: "active" },
    { id: "hotel-lamina", name: "Hotel Lamina", type: "Hotel", area: "Termini", rooms: 10, occupancy: 0.7, status: "active" },
    { id: "hotel-riva", name: "Hotel Riva", type: "Hotel", area: "Ostiense", rooms: 5, occupancy: 1, status: "attention" },
    ...vacationHomes,
    ...guesthouses,
  ];

  const cases = [
    {
      id: "case-smart-lock-timeout",
      scenarioId: "access-smartlock-timeout",
      flowId: "online-checkin",
      title: "Arrivo imminente, smart lock non risponde",
      guest: "Elena Mariani",
      bookingId: "BK-2406-1187",
      unit: "Affittacamere Tramonto - camera 7",
      propertyId: "affittacamere-tramonto",
      channel: "Booking.com",
      status: "at_risk",
      severity: "critica",
      eta: "18:20",
      owner: "AI Duty Manager",
      businessGoal: "guest_can_access_property",
      summary: "Ospite autorizzata, saldo chiuso e arrivo entro 40 minuti. Provider accessi in timeout dopo retry.",
      supervisorDecision: "Proteggere l'accesso ospite con codice manuale o chiave fisica. La issue smart lock resta in Technical Inbox.",
      nextBestActions: ["Avvia scenario runtime", "Preparare fallback accesso", "Notificare ospite su canale tracciato"],
      attention: ["SLA accesso 12 min", "Provider accessi instabile", "Ospite gia in viaggio"],
      conversation: [
        { actor: "Ospite", channel: "WhatsApp", text: "Arrivo alle 18:20, posso entrare direttamente?" },
        { actor: "AI", channel: "PMS", text: "Identita, saldo e finestra soggiorno verificati." },
      ],
      automations: ["guestPortal.getCheckinStatus", "access.createSmartLockLink", "guest.sendAccessInstructions", "pms.recordAccessDelivery"],
      fallback: ["Codice manuale", "Chiave fisica in lockbox", "Provider alternativo", "Host welcome"],
      successContract: "guest_can_access_property",
    },
    {
      id: "case-maintenance-vendor",
      scenarioId: "maintenance-vendor-failed",
      flowId: "maintenance",
      title: "Aria condizionata guasta, tecnico non disponibile",
      guest: "Nora Klein",
      bookingId: "BK-2406-1021",
      unit: "Hotel Velario - 204",
      propertyId: "hotel-velario",
      channel: "Expedia",
      status: "waiting_human",
      severity: "alta",
      eta: "14:05",
      owner: "Guest Recovery Agent",
      businessGoal: "guest_issue_is_safely_resolved",
      summary: "Guasto comfort in camera occupata. Vendor primario non accetta dispatch, serve alternativa operativa.",
      supervisorDecision: "Rimuovere l'impatto sul soggiorno prima di insistere sul vendor primario.",
      nextBestActions: ["Inviare tecnico alternativo", "Preparare cambio camera", "Comunicare ETA realistico"],
      attention: ["Camera occupata", "Rischio recensione negativa", "Temperatura esterna alta"],
      conversation: [
        { actor: "Ospite", channel: "OTA inbox", text: "Il condizionatore non parte e la stanza e molto calda." },
        { actor: "AI", channel: "Ops", text: "Camera equivalente 208 disponibile dalle 15:00." },
      ],
      automations: ["ops.createMaintenanceTicket", "vendor.dispatch", "guest.sendMaintenanceUpdate", "pms.recordIssueResolution"],
      fallback: ["Tecnico alternativo", "Cambio camera", "Ventilatore + late checkout", "Micro-compensazione secondo policy"],
      successContract: "guest_issue_is_safely_resolved",
    },
    {
      id: "case-refund-gateway",
      scenarioId: "refund-api-failed",
      flowId: "refund-request",
      title: "Rimborso approvato, gateway in errore",
      guest: "Marco Bellini",
      bookingId: "BK-2406-0974",
      unit: "Hotel Aurora - 312",
      propertyId: "hotel-aurora",
      channel: "Diretto",
      status: "at_risk",
      severity: "alta",
      eta: "16:00",
      owner: "Revenue Recovery Agent",
      businessGoal: "refund_request_is_resolved",
      summary: "Rimborso parziale approvato da policy; gateway pagamento risponde con errore permanente.",
      supervisorDecision: "Completare il rimborso o offrire equivalente approvato, senza bloccare la comunicazione al cliente.",
      nextBestActions: ["Avviare scenario rimborso", "Validare importo", "Usare gateway alternativo o voucher"],
      attention: ["Decisione economica tracciata", "Ospite attende conferma", "Issue gateway separata"],
      conversation: [
        { actor: "Ospite", channel: "Email", text: "Confermate il rimborso per la notte senza acqua calda?" },
        { actor: "AI", channel: "Policy", text: "Deroga approvata: 85 EUR." },
      ],
      automations: ["payment.executeRefund", "guest.sendRefundDecision", "pms.recordRefundResolution"],
      fallback: ["Rimborso manuale", "Gateway alternativo", "Voucher soggiorno", "Credito futuro"],
      successContract: "refund_request_is_resolved",
    },
    {
      id: "case-room-not-ready",
      scenarioId: null,
      flowId: "missed-cleaning",
      title: "Camera non pronta e ospite gia arrivato",
      guest: "Sofia De Luca",
      bookingId: "BK-2406-1214",
      unit: "Casa Campo de Fiori 12",
      propertyId: "roma-stay-campo-fiori",
      channel: "Airbnb",
      status: "attention",
      severity: "media",
      eta: "adesso",
      owner: "Housekeeping Coordinator",
      businessGoal: "guest_issue_is_safely_resolved",
      summary: "Turnover in ritardo, ospite in zona e messaggio con tono irritato.",
      supervisorDecision: "Evitare escalation reputazionale: deposito bagagli, ETA realistico e alternativa pronta se necessario.",
      nextBestActions: ["Assegnare runner", "Inviare update ospite", "Preparare compensazione minima se oltre policy"],
      attention: ["Ospite gia arrivato", "Housekeeping in ritardo", "Possibile review negativa"],
      conversation: [
        { actor: "Ospite", channel: "Airbnb", text: "Siamo sotto casa, ma la pulizia non sembra finita." },
        { actor: "AI", channel: "Ops", text: "Runner disponibile in 18 minuti." },
      ],
      automations: ["ops.assignTurnover", "guest.sendDelayUpdate", "pms.recordRecovery"],
      fallback: ["Deposito bagagli", "Camera equivalente", "Late checkout gratuito", "Micro-compensazione"],
      successContract: "guest_issue_is_safely_resolved",
    },
  ];

  const generatedTasks = properties.flatMap((property, index) => {
    const day = String(24 + (index % 5)).padStart(2, "0");
    const checkoutDay = String(25 + (index % 5)).padStart(2, "0");
    const roomLabel = property.type === "Casa vacanza" ? "Intero appartamento" : `Camera ${String((index % Math.max(property.rooms, 1)) + 1).padStart(2, "0")}`;
    const guestName = [
      "Giulia Conti", "Luca Ferri", "Marta Leone", "Andrea Moretti", "Chiara Rinaldi",
      "Paolo Greco", "Sara Fontana", "Davide Romano", "Laura Serra", "Matteo Costa",
    ][index % 10];
    return [
      {
        id: `task-${property.id}-arrival`,
        caseId: null,
        title: "Verificare arrivo e prerequisiti accesso",
        priority: index % 4 === 0 ? "alta" : "media",
        type: "Accessi",
        propertyId: property.id,
        room: roomLabel,
        unit: property.name,
        owner: "Reception remoto",
        due: `${String(14 + (index % 7)).padStart(2, "0")}:20`,
        arrivalTime: `${String(15 + (index % 6)).padStart(2, "0")}:00`,
        checkinDate: `2026-06-${day}`,
        checkoutDate: `2026-06-${checkoutDay}`,
        guest: guestName,
        bookingId: `AUTO-${String(index + 1).padStart(4, "0")}`,
        recommendation: "Controllare saldo, documento e canale ospite prima di inviare istruzioni di accesso.",
        status: "open",
      },
      {
        id: `task-${property.id}-turnover`,
        caseId: null,
        title: property.type === "Casa vacanza" ? "Confermare turnover appartamento" : "Confermare camera pronta",
        priority: index % 5 === 0 ? "alta" : "media",
        type: property.type === "Casa vacanza" ? "Housekeeping" : "Operations",
        propertyId: property.id,
        room: roomLabel,
        unit: property.name,
        owner: property.type === "Casa vacanza" ? "Runner zona" : "Housekeeping lead",
        due: `${String(11 + (index % 6)).padStart(2, "0")}:45`,
        arrivalTime: `${String(16 + (index % 5)).padStart(2, "0")}:30`,
        checkinDate: `2026-06-${day}`,
        checkoutDate: `2026-06-${checkoutDay}`,
        guest: guestName,
        bookingId: `AUTO-${String(index + 1).padStart(4, "0")}`,
        recommendation: "Verificare foto fine pulizia, dotazioni minime e disponibilita prima dell'arrivo.",
        status: "open",
      },
    ];
  });

  const tasks = [
    ...generatedTasks,
    { id: "task-access-lockbox", caseId: "case-smart-lock-timeout", title: "Preparare lockbox per arrivo imminente", priority: "critica", type: "Accessi", propertyId: "affittacamere-tramonto", room: "Camera 7", unit: "Affittacamere Tramonto - camera 7", owner: "Reception remoto", due: "18:08", arrivalTime: "18:20", checkinDate: "2026-06-24", checkoutDate: "2026-06-27", guest: "Elena Mariani", bookingId: "BK-2406-1187", recommendation: "Confermare codice lockbox, inviare SMS e registrare evidenza PMS.", status: "open" },
    { id: "task-ac-room-move", caseId: "case-maintenance-vendor", title: "Tenere camera alternativa pronta", priority: "alta", type: "Guest recovery", propertyId: "hotel-velario", room: "Camera 208", unit: "Hotel Velario - 208", owner: "Front desk", due: "14:20", arrivalTime: "gia in house", checkinDate: "2026-06-23", checkoutDate: "2026-06-26", guest: "Nora Klein", bookingId: "BK-2406-1021", recommendation: "Bloccare camera 208 finche il tecnico non conferma ETA affidabile.", status: "open" },
    { id: "task-refund-approval", caseId: "case-refund-gateway", title: "Validare rimborso manuale 85 EUR", priority: "alta", type: "Revenue", propertyId: "hotel-aurora", room: "Camera 312", unit: "Hotel Aurora - 312", owner: "Amministrazione", due: "16:00", arrivalTime: "soggiorno concluso", checkinDate: "2026-06-18", checkoutDate: "2026-06-21", guest: "Marco Bellini", bookingId: "BK-2406-0974", recommendation: "Usare riferimento pratica e inviare esito solo dopo prova transazione.", status: "open" },
    { id: "task-runner-cleaning", caseId: "case-room-not-ready", title: "Sbloccare turnover appartamento", priority: "media", type: "Housekeeping", propertyId: "roma-stay-campo-fiori", room: "Intero appartamento", unit: "Casa Campo de Fiori 12", owner: "Runner zona centro", due: "15:35", arrivalTime: "15:10", checkinDate: "2026-06-24", checkoutDate: "2026-06-29", guest: "Sofia De Luca", bookingId: "BK-2406-1214", recommendation: "Aggiornare ospite con ETA, offrire deposito bagagli e confermare foto fine pulizia.", status: "open" },
    { id: "task-night-audit", caseId: null, title: "Riconciliare 7 arrivi senza documento completo", priority: "alta", type: "Compliance", propertyId: "hotel-riva", room: "Camere 101-105", unit: "Hotel Riva", owner: "Night audit", due: "20:00", arrivalTime: "19:30-22:10", checkinDate: "2026-06-24", checkoutDate: "2026-06-25", guest: "Arrivi multipli", bookingId: "batch-2406", recommendation: "Priorita agli arrivi entro 2 ore; non inviare accessi finche identita non e verificata.", status: "open" },
    { id: "task-staff-routing", caseId: null, title: "Riassegnare 4 pulizie con SLA sotto 45 min", priority: "media", type: "Housekeeping", propertyId: "affittacamere-liberty", room: "Camere 2, 4, 6, 9", unit: "Affittacamere Liberty", owner: "Housekeeping lead", due: "17:10", arrivalTime: "17:40-19:00", checkinDate: "2026-06-24", checkoutDate: "2026-06-28", guest: "Turnover multipli", bookingId: "ops-2406", recommendation: "Spostare runner da Hotel Lamina e mantenere una camera buffer.", status: "open" },
  ];

  const agents = [
    { id: "supervisor", name: "AI Duty Manager", scope: "Outcome, priorita e interventi umani" },
    { id: "access", name: "Access & Arrival Agent", scope: "Identita, saldo, accessi e istruzioni" },
    { id: "recovery", name: "Guest Recovery Agent", scope: "Guasti, reclami e rischio reputazione" },
    { id: "revenue", name: "Revenue Recovery Agent", scope: "Pagamenti, rimborsi e decisioni economiche" },
    { id: "housekeeping", name: "Housekeeping Coordinator", scope: "Turnover, camere pronte e runner" },
  ];

  return { properties, cases, tasks, agents };
});
