(() => {
  const groups = [
    { id: "bookings", label: "Prenotazioni", description: "Acquisizione e variazioni" },
    { id: "pre-arrival", label: "Pre-arrivo", description: "Preparazione e servizi" },
    { id: "arrival-access", label: "Arrivi e accessi", description: "Ingresso e identita" },
    { id: "in-stay", label: "Durante il soggiorno", description: "Assistenza e recovery" },
    { id: "checkout", label: "Checkout", description: "Partenza e controlli" },
    { id: "operations", label: "Housekeeping e manutenzione", description: "Operazioni struttura" },
    { id: "revenue", label: "Pagamenti e revenue", description: "Incassi e ricavi" },
    { id: "post-stay", label: "Post-soggiorno e compliance", description: "Relazione e adempimenti" },
  ];

  const existing = {
    "online-checkin": { group: "arrival-access", category: "Accessi digitali", level: "Core" },
    "late-checkout": { group: "checkout", category: "Partenze flessibili", level: "Core" },
    maintenance: { group: "in-stay", category: "Guest recovery", level: "Core" },
    "transfer-upsell": { group: "pre-arrival", category: "Servizi ancillari", level: "Core" },
    "no-show-payment": { group: "revenue", category: "Rischio e pagamenti", level: "Avanzato" },
    "review-poststay": { group: "post-stay", category: "Reputazione", level: "Core" },
  };

  const specs = [
    {
      id: "new-booking-sync", name: "Nuova prenotazione confermata", group: "bookings", category: "Distribuzione", level: "Core",
      summary: "Normalizza la prenotazione OTA, assegna l'unita e avvia il journey ospite.", trigger: "booking.confirmed", role: "Booking Intake",
      objective: "trasformare ogni nuova prenotazione in una pratica operativa completa e senza duplicati",
      inputs: "payload OTA, calendario PMS, anagrafica ospite, tariffa, policy e disponibilita unita",
      steps: ["verifica riferimento OTA e possibili duplicati", "mappa tariffa, occupanti e richieste nel PMS", "assegna unita e task pre-arrivo", "invia conferma solo dopo la scrittura nel PMS"],
      guardrail: "Non creare una seconda pratica se OTA reference o email risultano gia associate allo stesso soggiorno", tool: "pms.createOrUpdateReservation", toolLabel: "Sincronizza prenotazione",
      params: { deduplicate_by: ["ota_reference", "stay_dates", "guest_email"], assign_unit: true }, template: "booking_confirmation_received", sla: "1 min", risk: "Medio",
    },
    {
      id: "booking-date-change", name: "Modifica date prenotazione", group: "bookings", category: "Variazioni", level: "Core",
      summary: "Ricalcola disponibilita, prezzo e impatto operativo prima di confermare nuove date.", trigger: "booking.change_requested", role: "Booking Change",
      objective: "gestire cambi data senza overbooking, errori tariffari o promesse non confermate",
      inputs: "date attuali e richieste, inventario, regole tariffarie, canale di vendita e task operativi",
      steps: ["controlla disponibilita sull'intero intervallo", "calcola differenza tariffaria e penali", "presenta importo e condizioni", "aggiorna PMS solo dopo accettazione"],
      guardrail: "Le prenotazioni OTA non rimborsabili seguono sempre workflow e autorizzazioni del canale", tool: "pms.quoteReservationChange", toolLabel: "Calcola variazione",
      params: { requested_dates: "{{request.dates}}", include_rate_difference: true, hold_minutes: 20 }, template: "booking_change_quote", sla: "5 min", risk: "Medio",
    },
    {
      id: "booking-cancellation", name: "Richiesta cancellazione", group: "bookings", category: "Cancellazioni", level: "Core",
      summary: "Applica la policy corretta, calcola il rimborso e libera l'inventario in sicurezza.", trigger: "booking.cancellation_requested", role: "Cancellation Desk",
      objective: "chiudere la prenotazione rispettando contratto, OTA e contabilita",
      inputs: "policy prenotata, finestra di cancellazione, pagamenti, canale, messaggi e assicurazione viaggio",
      steps: ["determina la policy applicabile", "calcola rimborso, penale e tempi", "chiede conferma per azioni irreversibili", "libera inventario e annulla task collegati"],
      guardrail: "Nessun rimborso o annullamento irreversibile senza richiesta autenticata e policy verificata", tool: "pms.calculateCancellation", toolLabel: "Calcola cancellazione",
      params: { include_payments: true, include_ota_rules: true, dry_run: true }, template: "cancellation_summary", sla: "10 min", risk: "Alto",
    },
    {
      id: "special-request-intake", name: "Richiesta speciale in prenotazione", group: "bookings", category: "Guest preferences", level: "Core",
      summary: "Classifica culla, allergie, letti separati e occasioni speciali creando task verificabili.", trigger: "booking.special_request_received", role: "Guest Preferences",
      objective: "convertire richieste libere in impegni operativi chiari senza promesse non verificate",
      inputs: "testo ospite, dotazioni unita, inventario extra, preferenze volontarie e roster staff",
      steps: ["estrae richieste e scadenze", "verifica disponibilita e costo", "crea task al reparto responsabile", "conferma solo gli elementi accettati"],
      guardrail: "Allergie e accessibilita sono esigenze operative; non dedurre o memorizzare diagnosi", tool: "ops.createSpecialRequestTasks", toolLabel: "Crea task richieste",
      params: { split_requests: true, require_department_ack: true }, template: "special_request_status", sla: "15 min", risk: "Medio",
    },
    {
      id: "overbooking-relocation", name: "Overbooking e ricollocazione", group: "bookings", category: "Inventory recovery", level: "Avanzato",
      summary: "Individua conflitti, valuta alternative equivalenti e coordina la ricollocazione.", trigger: "inventory.overbooking_detected", role: "Relocation Manager",
      objective: "risolvere un conflitto inventario minimizzando disagio, costo e rischio reputazionale",
      inputs: "prenotazioni coinvolte, priorita contrattuali, disponibilita interna, partner, tariffe e distanza",
      steps: ["valida che non sia un errore di sincronizzazione", "applica la policy di priorita", "prepara opzioni pari o superiori", "ottiene approvazione manager prima del contatto"],
      guardrail: "La selezione non usa dati sensibili e ogni ricollocazione richiede approvazione umana", tool: "inventory.buildRelocationOptions", toolLabel: "Trova ricollocazione",
      params: { minimum_quality: "same_or_better", max_distance_km: 5, include_transfer: true }, template: "relocation_proposal", sla: "10 min", risk: "Alto",
    },
    {
      id: "documents-incomplete", name: "Documenti pre-arrivo incompleti", group: "pre-arrival", category: "Identificazione", level: "Core",
      summary: "Ricorda solo i dati mancanti e apre assistenza se il guest portal non funziona.", trigger: "arrival.minus_24h.documents_missing", role: "Pre-arrival Compliance",
      objective: "completare gli adempimenti prima dell'arrivo con il minimo attrito",
      inputs: "stato guest portal, occupanti, requisiti locali, lingua e cronologia reminder",
      steps: ["identifica i campi mancanti", "distingue errore tecnico da mancata compilazione", "invia un link sicuro", "crea task staff se il check-in e imminente"],
      guardrail: "Non inviare documenti o numeri identificativi via chat e non superare due reminder", tool: "guestPortal.createCompletionLink", toolLabel: "Genera link documenti",
      params: { fields: "{{compliance.missing_fields}}", expires_in_hours: 24, secure_session: true }, template: "documents_missing_reminder", sla: "5 min", risk: "Medio",
    },
    {
      id: "arrival-eta-collection", name: "Raccolta orario di arrivo", group: "pre-arrival", category: "Pianificazione", level: "Core",
      summary: "Raccoglie ETA e mezzo di trasporto per coordinare accoglienza e camera pronta.", trigger: "arrival.minus_48h.eta_missing", role: "Arrival Planner",
      objective: "ottenere un orario di arrivo affidabile con una sola interazione semplice",
      inputs: "dati viaggio gia presenti, check-in window, lingua, reception e stato camera",
      steps: ["cerca ETA in note e messaggi", "chiede solo le informazioni mancanti", "normalizza fuso orario", "aggiorna accoglienza e pulizie"],
      guardrail: "Non tracciare voli o spostamenti senza un riferimento fornito volontariamente", tool: "pms.updateArrivalEstimate", toolLabel: "Aggiorna ETA",
      params: { eta: "{{request.extracted_eta}}", transport: "{{request.transport}}", notify_ops: true }, template: "arrival_eta_request", sla: "10 min", risk: "Basso",
    },
    {
      id: "arrival-instructions", name: "Istruzioni di arrivo contestuali", group: "pre-arrival", category: "Guest journey", level: "Core",
      summary: "Invia percorso, parcheggio e ingresso adattati a orario e mezzo dell'ospite.", trigger: "arrival.minus_6h.instructions_due", role: "Arrival Concierge",
      objective: "far arrivare l'ospite senza frizioni con indicazioni brevi e corrette",
      inputs: "ETA, mezzo, meteo, viabilita nota, accessibilita, indirizzo e modalita ingresso",
      steps: ["sceglie il percorso adatto", "include solo istruzioni rilevanti", "segnala ZTL o parcheggio", "aggiunge contatto operativo e piano B"],
      guardrail: "Usa solo indicazioni verificate e non promette parcheggi non prenotati", tool: "guest.buildArrivalGuide", toolLabel: "Crea guida arrivo",
      params: { transport: "{{arrival.transport}}", language: "{{guest.language}}", include_live_constraints: true }, template: "contextual_arrival_guide", sla: "5 min", risk: "Basso",
    },
    {
      id: "experience-upsell", name: "Upsell esperienza locale", group: "pre-arrival", category: "Servizi ancillari", level: "Core",
      summary: "Propone un'esperienza coerente con soggiorno e preferenze senza pressione commerciale.", trigger: "arrival.minus_72h.experience_match", role: "Experience Concierge",
      objective: "proporre un solo servizio realmente utile aumentando il ricavo ancillare",
      inputs: "durata soggiorno, composizione gruppo, preferenze esplicite, partner e meteo",
      steps: ["esclude offerte incompatibili", "seleziona la migliore proposta", "mostra prezzo e condizioni", "limita il follow-up a uno"],
      guardrail: "Niente scarsita artificiale, profilazione sensibile o messaggi dopo opt-out", tool: "concierge.getExperienceQuote", toolLabel: "Prepara esperienza",
      params: { party_size: "{{booking.guest_count}}", max_results: 1 }, template: "local_experience_offer", sla: "20 min", risk: "Basso",
    },
    {
      id: "room-not-ready", name: "Camera non pronta all'arrivo", group: "arrival-access", category: "Arrival recovery", level: "Core",
      summary: "Ricalcola ETA camera, offre deposito bagagli e mantiene aggiornato l'ospite.", trigger: "guest.arrived.room_not_ready", role: "Arrival Recovery",
      objective: "gestire il ritardo camera con tempi realistici e una soluzione subito utile",
      inputs: "stato housekeeping, ETA completamento, aree disponibili, ticket e storico messaggi",
      steps: ["conferma lo stato con housekeeping", "calcola un ETA prudente", "offre deposito bagagli", "programma aggiornamenti fino a camera pronta"],
      guardrail: "Compensazioni sopra soglia richiedono approvazione; mai inventare un orario", tool: "housekeeping.escalateRoomReadiness", toolLabel: "Sollecita camera",
      params: { priority: "arrival_waiting", request_eta: true, notify_frontdesk: true }, template: "room_not_ready_update", sla: "3 min", risk: "Alto",
    },
    {
      id: "early-checkin", name: "Richiesta early check-in", group: "arrival-access", category: "Arrivi flessibili", level: "Core",
      summary: "Verifica occupazione e pulizie, quindi conferma ingresso anticipato o alternative.", trigger: "guest.request.early_checkin", role: "Early Arrival",
      objective: "concedere ingresso anticipato solo quando camera e operations lo permettono",
      inputs: "checkout precedente, stato pulizia, priorita reparto, deposito bagagli e policy tariffaria",
      steps: ["verifica che l'ospite precedente sia uscito", "ottiene ETA housekeeping", "calcola eventuale fee", "propone deposito bagagli se necessario"],
      guardrail: "Non attivare accessi prima della conferma room-ready nel PMS", tool: "housekeeping.checkEarlyArrival", toolLabel: "Verifica camera pronta",
      params: { requested_at: "{{request.early_checkin_at}}", include_fee: true, hold_minutes: 15 }, template: "early_checkin_response", sla: "5 min", risk: "Medio",
    },
    {
      id: "guest-locked-out", name: "Ospite bloccato fuori", group: "arrival-access", category: "Access emergency", level: "Core",
      summary: "Verifica identita e serratura, rigenera accesso o attiva assistenza urgente.", trigger: "guest.report.locked_out", role: "Access Emergency",
      objective: "ripristinare l'accesso rapidamente senza ridurre la sicurezza",
      inputs: "prenotazione attiva, telefono verificato, log serratura, batteria, rete e reperibilita",
      steps: ["autentica l'ospite con segnali disponibili", "controlla porta e ultimo codice", "rigenera un accesso breve", "attiva reperibilita se il lock non risponde"],
      guardrail: "Mai comunicare master code; identita dubbia o porta forzata passano allo staff", tool: "access.restoreGuestAccess", toolLabel: "Ripristina accesso",
      params: { validity_minutes: 30, revoke_previous: true, require_verified_phone: true }, template: "access_restored_or_assistance_eta", sla: "2 min", risk: "Alto",
    },
    {
      id: "identity-mismatch", name: "Incongruenza identita all'arrivo", group: "arrival-access", category: "Security review", level: "Avanzato",
      summary: "Blocca l'accesso automatico e raccoglie evidenze minime per una verifica umana.", trigger: "arrival.identity_mismatch", role: "Identity Review",
      objective: "risolvere discrepanze senza accuse o esposizione di dati",
      inputs: "nome prenotante, ospiti dichiarati, verifica portale, OTA e contatti autenticati",
      steps: ["classifica la discrepanza", "contatta il prenotante verificato", "raccoglie la prova minima", "prepara un riepilogo per lo staff"],
      guardrail: "Nessun accesso automatico, nessun documento in chat e decisione finale umana", tool: "security.createIdentityReview", toolLabel: "Apri verifica identita",
      params: { freeze_access: true, notify_duty_manager: true, evidence_minimization: true }, template: "identity_review_in_progress", sla: "2 min", risk: "Alto",
    },
    {
      id: "noise-complaint", name: "Reclamo per rumore", group: "in-stay", category: "Guest recovery", level: "Core",
      summary: "Distingue rumore interno ed esterno, interviene e verifica la risoluzione.", trigger: "guest.report.noise", role: "Quiet Hours Response",
      objective: "ripristinare il riposo con un intervento proporzionato e documentato",
      inputs: "orario, unita coinvolte, quiet hours, sensori non invasivi, storico e reperibilita",
      steps: ["localizza la fonte senza accusare", "applica il primo intervento", "scala quando necessario", "ricontatta l'ospite dopo quindici minuti"],
      guardrail: "Mai condividere identita di altri ospiti o usare registrazioni audio", tool: "ops.openNoiseIncident", toolLabel: "Apri incidente rumore",
      params: { quiet_hours_policy: true, schedule_followup_minutes: 15, notify_duty_manager: true }, template: "noise_incident_update", sla: "3 min", risk: "Alto",
    },
    {
      id: "concierge-request", name: "Richiesta concierge in soggiorno", group: "in-stay", category: "Guest service", level: "Core",
      summary: "Risponde con opzioni verificate per ristoranti, trasporti e servizi locali.", trigger: "guest.request.concierge", role: "Local Concierge",
      objective: "fornire una risposta utile coerente con preferenze e vincoli dichiarati",
      inputs: "richiesta, posizione, orario, budget esplicito, partner verificati e disponibilita",
      steps: ["chiarisce un solo vincolo se indispensabile", "propone massimo tre opzioni", "distingue disponibilita da suggerimento", "registra preferenze utili"],
      guardrail: "Non inventare orari o disponibilita e non dedurre dati sensibili", tool: "concierge.searchVerifiedOptions", toolLabel: "Cerca opzioni verificate",
      params: { max_results: 3, require_open_now_check: true, include_distance: true }, template: "concierge_recommendations", sla: "5 min", risk: "Basso",
    },
    {
      id: "room-change", name: "Richiesta cambio camera", group: "in-stay", category: "Inventory recovery", level: "Avanzato",
      summary: "Valuta motivazione, disponibilita, pulizie e differenze tariffarie prima del trasferimento.", trigger: "guest.request.room_change", role: "Room Move Coordinator",
      objective: "risolvere il problema coordinando inventario e reparti senza nuovi conflitti",
      inputs: "motivo, camere disponibili, stato pulizia, categoria tariffaria, accessi e bagagli",
      steps: ["valuta se risolvere in camera", "seleziona alternativa compatibile", "ottiene approvazione per upgrade", "coordina accessi, pulizia e spostamento"],
      guardrail: "Non assegnare camere occupate o non ispezionate; differenze economiche esplicite", tool: "pms.prepareRoomMove", toolLabel: "Prepara cambio camera",
      params: { require_room_ready: true, migrate_access: true, create_housekeeping_tasks: true }, template: "room_move_plan", sla: "10 min", risk: "Alto",
    },
    {
      id: "stay-extension", name: "Estensione del soggiorno", group: "in-stay", category: "Revenue ops", level: "Core",
      summary: "Controlla disponibilita continua, quota nuove notti e aggiorna accessi dopo pagamento.", trigger: "guest.request.extend_stay", role: "Stay Extension",
      objective: "vendere notti aggiuntive proteggendo inventario, tariffa e operations",
      inputs: "calendario, restrizioni tariffarie, task checkout, pagamento e accessi",
      steps: ["verifica disponibilita nella stessa unita", "calcola tariffa e tasse", "offre cambio camera se necessario", "estende accessi dopo conferma economica"],
      guardrail: "Disponibilita bloccata per tempo limitato e mai confermata senza garanzia", tool: "pms.quoteStayExtension", toolLabel: "Quota estensione",
      params: { requested_checkout: "{{request.new_checkout}}", hold_minutes: 15, include_taxes: true }, template: "stay_extension_offer", sla: "5 min", risk: "Medio",
    },
    {
      id: "checkout-reminder", name: "Promemoria checkout", group: "checkout", category: "Departure journey", level: "Core",
      summary: "Invia orario, istruzioni chiavi e opzioni bagagli senza messaggi ridondanti.", trigger: "checkout.minus_18h", role: "Departure Assistant",
      objective: "rendere la partenza semplice e puntuale con istruzioni pertinenti",
      inputs: "orario checkout, accesso, servizi acquistati, deposito bagagli e lingua",
      steps: ["verifica late checkout confermati", "include solo azioni richieste", "offre deposito bagagli", "chiede una conferma rapida"],
      guardrail: "Non inviare durante quiet hours o a soggiorni gia chiusi", tool: "guest.buildCheckoutGuide", toolLabel: "Prepara istruzioni",
      params: { include_key_return: true, include_luggage_option: true }, template: "checkout_reminder", sla: "15 min", risk: "Basso",
    },
    {
      id: "checkout-extras", name: "Extra non saldati al checkout", group: "checkout", category: "Payment recovery", level: "Core",
      summary: "Riconcilia consumi e servizi, invia riepilogo e link di pagamento tracciabile.", trigger: "checkout.balance_due", role: "Checkout Billing",
      objective: "chiudere il conto con addebiti verificabili e comunicazione trasparente",
      inputs: "folio PMS, minibar, servizi, ricevute, autorizzazioni e contestazioni",
      steps: ["riconcilia ogni voce", "rimuove duplicati", "genera riepilogo leggibile", "passa allo staff le contestazioni"],
      guardrail: "Nessun addebito senza descrizione e prova; dispute aperte bloccano la capture", tool: "payment.createCheckoutBalanceLink", toolLabel: "Crea saldo checkout",
      params: { include_itemized_folio: true, expires_in_hours: 24, allow_dispute: true }, template: "checkout_balance_due", sla: "5 min", risk: "Alto",
    },
    {
      id: "lost-and-found", name: "Oggetto dimenticato", group: "checkout", category: "Lost and found", level: "Core",
      summary: "Cerca l'oggetto, documenta custodia e organizza ritiro o spedizione pagata.", trigger: "guest.report.lost_item", role: "Lost and Found",
      objective: "ricongiungere l'ospite con l'oggetto mantenendo tracciabilita e privacy",
      inputs: "descrizione, camera, data partenza, log housekeeping, foto e spedizioni",
      steps: ["raccoglie descrizione identificativa", "apre ricerca con housekeeping", "confronta senza esporre oggetti altrui", "organizza consegna dopo verifica"],
      guardrail: "Documenti, chiavi, farmaci e valori seguono custodia rinforzata", tool: "ops.createLostFoundCase", toolLabel: "Apri pratica oggetto",
      params: { notify_housekeeping: true, retention_days: 90, require_chain_of_custody: true }, template: "lost_item_case_update", sla: "20 min", risk: "Medio",
    },
    {
      id: "post-checkout-damage", name: "Danno rilevato dopo il checkout", group: "checkout", category: "Damage management", level: "Avanzato",
      summary: "Raccoglie prove, distingue usura e prepara una pratica prima dell'addebito.", trigger: "housekeeping.damage_reported", role: "Damage Review",
      objective: "valutare un danno in modo equo, documentato e conforme al canale",
      inputs: "foto timestamp, inventario precedente, manutenzioni, deposito, policy e preventivo",
      steps: ["verifica che il danno sia nuovo", "distingue usura ordinaria", "raccoglie costo di ripristino", "prepara pratica per revisione umana"],
      guardrail: "Nessun addebito automatico; servono evidenze e approvazione manager", tool: "risk.buildDamageClaim", toolLabel: "Prepara pratica danno",
      params: { require_before_after_evidence: true, require_quote: true, human_approval: true }, template: "damage_claim_review_notice", sla: "30 min", risk: "Alto",
    },
    {
      id: "turnover-assignment", name: "Assegnazione turnover giornaliero", group: "operations", category: "Housekeeping planning", level: "Core",
      summary: "Ordina le camere per arrivo, complessita e posizione e assegna il team.", trigger: "housekeeping.daily_plan_due", role: "Housekeeping Planner",
      objective: "costruire un piano pulizie realistico per rendere pronte le camere urgenti",
      inputs: "partenze, arrivi, ETA, tipologia unita, durata, team e spostamenti",
      steps: ["calcola priorita room-ready", "stima carico per addetto", "minimizza spostamenti", "segnala capacita insufficiente"],
      guardrail: "Non assegnare carichi oltre turno o competenze", tool: "housekeeping.buildDailyRoster", toolLabel: "Genera piano pulizie",
      params: { optimize_routes: true, respect_shifts: true, include_inspections: true }, messageTool: "team.notify", template: "daily_housekeeping_roster", sla: "10 min", risk: "Medio",
    },
    {
      id: "missed-cleaning", name: "Pulizia saltata o in ritardo", group: "operations", category: "Housekeeping exception", level: "Core",
      summary: "Riassegna il task, protegge l'ETA camera e informa front desk.", trigger: "housekeeping.task_overdue", role: "Housekeeping Exception",
      objective: "recuperare un turnover in ritardo preservando qualita e promessa check-in",
      inputs: "task, posizione staff, priorita, ETA ospiti e fornitori backup",
      steps: ["conferma il ritardo reale", "stima impatto", "riassegna o attiva backup", "aggiorna front desk e ospite"],
      guardrail: "La velocita non riduce checklist igienica o ispezione", tool: "housekeeping.recoverOverdueTask", toolLabel: "Recupera task pulizia",
      params: { allow_reassignment: true, call_backup_after_minutes: 15, preserve_checklist: true }, messageTool: "team.notify", template: "housekeeping_delay_alert", sla: "5 min", risk: "Alto",
    },
    {
      id: "linen-inventory", name: "Scorta biancheria sotto soglia", group: "operations", category: "Inventory control", level: "Core",
      summary: "Prevede fabbisogno, consolida riordino e segnala rischi per i turnover.", trigger: "inventory.linen_below_threshold", role: "Linen Inventory",
      objective: "evitare rotture di stock usando occupazione e tempi reali di lavanderia",
      inputs: "giacenza, par level, camere in arrivo, fuori uso, lead time e ordini",
      steps: ["riconcilia consumo e giacenza", "calcola fabbisogno a sette giorni", "verifica ordini aperti", "propone trasferimento o riordino"],
      guardrail: "Ordini sopra budget richiedono approvazione", tool: "inventory.createLinenReplenishment", toolLabel: "Prepara riordino",
      params: { forecast_days: 7, consolidate_open_orders: true, require_budget_check: true }, messageTool: "team.notify", template: "linen_stock_action", sla: "2 ore", risk: "Medio",
    },
    {
      id: "preventive-maintenance", name: "Manutenzione preventiva programmata", group: "operations", category: "Asset maintenance", level: "Avanzato",
      summary: "Trova finestre senza ospiti e coordina tecnico, accessi e blocco inventario.", trigger: "asset.maintenance_due", role: "Preventive Maintenance Planner",
      objective: "eseguire manutenzione prima del guasto con minimo impatto commerciale",
      inputs: "scadenze asset, occupazione, durata, tecnico, ricambi e storico guasti",
      steps: ["valuta criticita e tolleranza", "trova la finestra libera", "blocca unita per il necessario", "coordina tecnico e ispezione finale"],
      guardrail: "Interventi obbligatori di sicurezza non possono essere rinviati", tool: "maintenance.schedulePreventiveWork", toolLabel: "Pianifica intervento",
      params: { optimize_for_occupancy: true, include_parts_check: true, require_post_inspection: true }, messageTool: "team.notify", template: "preventive_work_plan", sla: "4 ore", risk: "Medio",
    },
    {
      id: "room-inspection", name: "Ispezione camera post-pulizia", group: "operations", category: "Quality control", level: "Core",
      summary: "Campiona camere a rischio, verifica checklist e riapre task non conformi.", trigger: "housekeeping.task_completed", role: "Room Quality Control",
      objective: "intercettare non conformita prima che la camera venga marcata pronta",
      inputs: "checklist, foto, storico operativo, manutenzioni, arrivo e standard",
      steps: ["calcola priorita di ispezione", "verifica elementi obbligatori", "riapre task con difetti specifici", "marca pronta dopo esito positivo"],
      guardrail: "Valuta il lavoro e la camera, senza punteggi personali opachi", tool: "housekeeping.runRoomInspection", toolLabel: "Esegui controllo qualita",
      params: { risk_based_sampling: true, require_photo_for_failure: true, update_room_status: true }, messageTool: "team.notify", template: "room_inspection_result", sla: "10 min", risk: "Medio",
    },
    {
      id: "card-declined", name: "Carta rifiutata prima dell'arrivo", group: "revenue", category: "Payment recovery", level: "Core",
      summary: "Richiede un metodo valido, rispetta la deadline e protegge la prenotazione.", trigger: "payment.card_declined", role: "Payment Recovery",
      objective: "recuperare il pagamento senza esporre dati carta o cancellare prematuramente",
      inputs: "esito gateway, importo, deadline OTA, tentativi, rischio e canale autenticato",
      steps: ["classifica il rifiuto", "genera un link sicuro", "comunica la scadenza reale", "scala o cancella secondo policy"],
      guardrail: "Mai chiedere numeri carta in chat; tentativi e scadenze seguono gateway e OTA", tool: "payment.createSecureUpdateLink", toolLabel: "Crea link pagamento",
      params: { purpose: "update_payment_method", expires_in_hours: 12, pci_hosted: true }, template: "payment_method_update_required", sla: "3 min", risk: "Alto",
    },
    {
      id: "security-deposit", name: "Deposito cauzionale", group: "revenue", category: "Risk controls", level: "Core",
      summary: "Pre-autorizza, monitora scadenza e rilascia il deposito dopo controllo camera.", trigger: "arrival.deposit_due", role: "Deposit Manager",
      objective: "gestire la cauzione con importo, consenso e rilascio tracciabili",
      inputs: "policy tariffa, importo, gateway, checkout, ispezione e contestazioni",
      steps: ["verifica che la cauzione sia prevista", "crea pre-autorizzazione", "monitora validita", "rilascia dopo esito camera"],
      guardrail: "Nessuna capture automatica per danni e nessun deposito non contrattuale", tool: "payment.authorizeSecurityDeposit", toolLabel: "Pre-autorizza deposito",
      params: { capture: false, release_after_room_clear: true, notify_before_expiry: true }, template: "security_deposit_status", sla: "5 min", risk: "Alto",
    },
    {
      id: "refund-request", name: "Richiesta rimborso", group: "revenue", category: "Dispute handling", level: "Avanzato",
      summary: "Ricostruisce fatti e policy, propone una soluzione e passa l'esecuzione allo staff.", trigger: "guest.request.refund", role: "Refund Review",
      objective: "valutare la richiesta in modo coerente, empatico e difendibile",
      inputs: "motivazione, timeline, ticket, messaggi, policy, pagamenti e compensazioni",
      steps: ["riassume la richiesta", "verifica evidenze", "calcola opzioni di policy", "raccomanda una soluzione per approvazione"],
      guardrail: "L'agente non esegue rimborsi; importi e deroghe richiedono doppio controllo", tool: "recovery.buildRefundRecommendation", toolLabel: "Prepara proposta rimborso",
      params: { include_evidence_timeline: true, human_approval: true, prevent_duplicates: true }, template: "refund_request_acknowledged", sla: "30 min", risk: "Alto",
    },
    {
      id: "gap-night-pricing", name: "Offerta per notte invenduta", group: "revenue", category: "Revenue optimization", level: "Avanzato",
      summary: "Individua gap di una notte e propone estensione entro floor price e consenso.", trigger: "revenue.gap_night_detected", role: "Gap Night Revenue",
      objective: "monetizzare notti isolate con un'offerta utile a ospiti adiacenti",
      inputs: "occupazione, floor price, turnover, prenotazioni confinanti e opt-in",
      steps: ["verifica la notte vendibile", "calcola il minimo profittevole", "sceglie un ospite adiacente", "invia una sola offerta"],
      guardrail: "Nessuna discriminazione su dati sensibili e nessuna offerta sotto floor", tool: "pricing.createGapNightOffer", toolLabel: "Genera offerta notte",
      params: { respect_floor_price: true, adjacent_guests_only: true, expires_in_hours: 12 }, template: "gap_night_extension_offer", sla: "1 ora", risk: "Medio",
    },
    {
      id: "invoice-request", name: "Richiesta fattura", group: "post-stay", category: "Accounting", level: "Core",
      summary: "Raccoglie i dati fiscali mancanti, genera bozza e consegna il documento.", trigger: "guest.request.invoice", role: "Guest Accounting",
      objective: "emettere il documento fiscale corretto senza errori o duplicazioni",
      inputs: "folio, pagamenti, intestazione, paese fiscale, SDI o PEC e documenti emessi",
      steps: ["identifica il documento", "chiede solo i campi mancanti", "valida totali e imposte", "genera bozza nel gestionale"],
      guardrail: "Dati fiscali completi non vanno copiati in note PMS o chat non protette", tool: "accounting.createInvoiceDraft", toolLabel: "Crea bozza fattura",
      params: { validate_tax_identity: true, prevent_duplicates: true, attach_folio: true }, template: "invoice_ready", sla: "2 ore", risk: "Medio",
    },
    {
      id: "tourist-tax-report", name: "Riconciliazione tassa di soggiorno", group: "post-stay", category: "Local compliance", level: "Avanzato",
      summary: "Calcola imponibili ed esenzioni e prepara il riepilogo periodico.", trigger: "compliance.tourist_tax_period_due", role: "Tourist Tax Compliance",
      objective: "riconciliare soggiorni, incassi ed esenzioni in modo verificabile",
      inputs: "presenze, notti imponibili, esenzioni documentate e incassi",
      steps: ["applica regole del comune", "separa esenzioni con evidenza", "confronta PMS e pagamenti", "segnala scarti prima dell'invio"],
      guardrail: "Prepara il report ma non invia dichiarazioni senza revisione", tool: "compliance.buildTouristTaxReport", toolLabel: "Prepara report imposta",
      params: { reconcile_payments: true, flag_missing_exemptions: true, human_review: true }, messageTool: "team.notify", template: "tourist_tax_report_ready", sla: "1 giorno", risk: "Alto",
    },
    {
      id: "guest-registration", name: "Invio schedine autorita", group: "post-stay", category: "Public safety compliance", level: "Avanzato",
      summary: "Valida presenze e prepara l'invio alle autorita con audit degli errori.", trigger: "compliance.guest_registration_due", role: "Guest Registration Compliance",
      objective: "trasmettere i dati obbligatori completi entro i termini con minima esposizione",
      inputs: "ospiti presenti, documenti verificati, regole, deadline e ricevute",
      steps: ["controlla completezza", "normalizza secondo schema", "blocca record incoerenti", "invia e conserva ricevuta"],
      guardrail: "Credenziali e documenti restano nel vault; errori richiedono revisione umana", tool: "compliance.submitGuestRegistration", toolLabel: "Trasmetti registrazioni",
      params: { validate_schema: true, use_secret_vault: true, store_receipt: true }, messageTool: "team.notify", template: "guest_registration_receipt", sla: "30 min", risk: "Alto",
    },
    {
      id: "privacy-retention", name: "Scadenza conservazione dati ospite", group: "post-stay", category: "Privacy operations", level: "Core",
      summary: "Applica retention per finalita, anonimizza dati scaduti e conserva audit minimale.", trigger: "privacy.retention_review_due", role: "Privacy Retention",
      objective: "ridurre i dati conservati rispettando obblighi e consensi",
      inputs: "categorie dati, finalita, base giuridica, scadenze, legal hold e sistemi",
      steps: ["classifica per finalita", "esclude obblighi e legal hold", "anonimizza nei sistemi previsti", "registra esito minimale"],
      guardrail: "Cancellazioni massive o conflitti di policy passano al privacy owner", tool: "privacy.executeRetentionPolicy", toolLabel: "Applica retention",
      params: { dry_run_first: true, respect_legal_hold: true, create_audit_record: true }, messageTool: "team.notify", template: "privacy_retention_summary", sla: "1 giorno", risk: "Alto",
    },
  ];

  function createFlow(spec) {
    const ids = {
      trigger: `${spec.id}-trigger`,
      agent: `${spec.id}-agent`,
      guardrail: `${spec.id}-guardrail`,
      tool: `${spec.id}-tool`,
      message: `${spec.id}-message`,
    };
    const procedure = spec.steps.map((step, index) => `${index + 1}. ${step}.`).join("\n");

    return {
      id: spec.id,
      name: spec.name,
      group: spec.group,
      category: spec.category,
      level: spec.level,
      summary: spec.summary,
      trigger: spec.trigger,
      metrics: { sla: spec.sla, risk: spec.risk, automations: "2 tool" },
      simulationOrder: Object.values(ids),
      edges: [[ids.trigger, ids.agent], [ids.agent, ids.guardrail], [ids.guardrail, ids.tool], [ids.tool, ids.message]],
      nodes: [
        {
          id: ids.trigger, type: "trigger", x: 42, y: 252, name: spec.name,
          description: `Evento operativo in ingresso: ${spec.summary}`,
          condition: "property.status == 'active'", params: { event: spec.trigger, source: "PMS + operations", booking_id: "{{booking.id}}" },
          guardrail: "Il payload viene deduplicato e validato prima di avviare il flusso.",
        },
        {
          id: ids.agent, type: "agent", x: 326, y: 112, name: `Agente ${spec.role}`,
          description: `Analizza il caso e decide come ${spec.objective}.`, condition: "event.validation == 'pass'",
          prompt: `Sei il sotto-agente ${spec.role} di una struttura hospitality italiana.\n\nObiettivo: ${spec.objective}.\n\nContesto disponibile: ${spec.inputs}. Usa solo dati presenti nei sistemi collegati; se manca un dato decisivo, chiedilo oppure passa il caso allo staff.\n\nProcedura:\n${procedure}\n\nRegole operative: ${spec.guardrail}. Comunica nella lingua preferita dell'ospite con tono calmo, concreto e non difensivo. Non dichiarare mai completata un'azione finche il relativo tool non restituisce esito positivo. Registra nel PMS decisioni, eccezioni e fallback umano.`,
          guardrail: spec.guardrail,
        },
        {
          id: ids.guardrail, type: "guardrail", x: 326, y: 392, name: "Verifica policy e approvazioni",
          description: "Controlla prerequisiti, soglie economiche, privacy e casi da passare allo staff.",
          condition: "agent.confidence >= 0.85 && policy.status == 'verified'",
          params: { checks: ["policy", "authorization", "data_minimization", "human_threshold"], failure_route: "ops.createStaffTask" },
          guardrail: spec.guardrail,
        },
        {
          id: ids.tool, type: "tool", x: 618, y: 154, name: spec.toolLabel,
          description: `Esegue l'azione operativa principale tramite ${spec.tool}.`, condition: "guardrail.status == 'pass'", tool: spec.tool,
          params: { booking_id: "{{booking.id}}", ...spec.params },
          guardrail: "Verifica la risposta del tool e annota l'esito; timeout o errore aprono un task allo staff.",
        },
        {
          id: ids.message, type: "message", x: 900, y: 252,
          name: spec.messageTool === "team.notify" ? "Notifica team e registra" : "Aggiorna ospite e PMS",
          description: "Comunica l'esito sul canale corretto e chiude il ciclo con una nota operativa.",
          condition: "tool.status in ['succeeded','needs_attention']", tool: spec.messageTool || "guest.sendMessage",
          params: { template: spec.template, language: "{{guest.language}}", add_pms_timeline_note: true },
          guardrail: "Invia solo dati necessari e non nasconde errori o azioni ancora in attesa.",
        },
      ],
    };
  }

  window.BNBFLOW_CATALOG = { groups, existing, flows: specs.map(createFlow) };
})();
